### ISSUE TITLE
I need to add some images here

### ISSUE THREAD

**Issue by robfalla** [scrumit/scrumseeker#1]
So... How?

**Comment by scrumit** [comment]
basically you add the images to the github repo and reference them.

https://guides.github.com/features/mastering-markdown/

Here's the markdown that would be used:

`-- ![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)`
 resulting in 
![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)
